apiVersion: v1
kind: Secret
metadata:
  name: xtradb-secrets
type: Opaque
stringData:
  root: uvb3mcMRB3ASEWqSs0URPvtWq9Py0w
  xtrabackup: k66uxYPrq8/gVopdBmGdxNtv8uo
  monitor: KOAEs4joL3SpLAOtYtYcyHNO
  proxyadmin: St1Lv2TI9KVPHvcCJ0sgNDMF
#  pmmserverkey: my_pmm_server_key
#  pmmservertoken: my_pmm_server_token
  operator: TcUgudWQT/sgM+XLIUaCzDAM
  replication: m0cyPnfl+nwQX0Rmvi7dnG6b
